language: "node_js"
node_js:
  - 0.11
  - 0.12

addons:
  postgresql: "9.4"

env:
  - DATABASE_URL=postgres://postgres@127.0.0.1:5432/sequelize_test

before_script:
  - "psql -c 'create database sequelize_test;' -U postgres"

after_script:
  - cat coverage/lcov.info | codeclimate

branches:
  only:
    - master
    - develop

addons:
  code_climate:
    repo_token: 31cc6f073f2f3a0dd4f938cf3d2723c305555dc86badc4cc1711b707df01fe40